### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by hahatiantang** [GiterLab/cordova-plugin-acmp#8]
`2 actionable tasks: 1 executed, 1 up-to-date
Error during processing of action! Attempting to revert...
Failed to install 'org.giterlab.pushplugin': CordovaError: Uh oh!
"/Users/ycl/qtpj/YJTeacher/platforms/android/org.giterlab.pushplugin/teacher-push.gradle" already exists!
    at copyNewFile (/Users/ycl/qtpj/YJTeacher/platforms/android/cordova/lib/pluginHandlers.js:245:45)
    at install (/Users/ycl/qtpj/YJTeacher/platforms/android/cordova/lib/pluginHandlers.js:91:17)
    at ActionStack.process (/Users/ycl/qtpj/YJTeacher/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/ycl/qtpj/YJTeacher/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/ycl/qtpj/YJTeacher/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Users/ycl/qtpj/YJTeacher/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/Users/ycl/qtpj/YJTeacher/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/ycl/qtpj/YJTeacher/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/ycl/qtpj/YJTeacher/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/ycl/qtpj/YJTeacher/platforms/android/cordova/node_modules/q/q.js:624:44`

请问是什么问题

**Comment by MWangxj** [comment]
你把你的platforms清空，然后plugin ls看看是否安装成功，pushplugin卸载再安装一下看一看
